cc_test(
    name = "grid_arithmetic_tests",
    srcs = ["arithmetic_tests.cc"],
    deps = [
        "//common/tests:common_tests",
        "//grid",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "grid_reshapers_tests",
    srcs = ["reshapers_tests.cc"],
    deps = [
        "//common/tests:common_tests",
        "//grid",
        "@gtest//:gtest_main",
    ],
)
