cc_library(
    name = "common_tests",
    srcs = ["common_tests.cc"],
    hdrs = ["common_tests.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//grid",
        "@gtest",
    ],
)
