
cc_library(
    name = "tests",
    srcs = ["src/arithmetic_tests.cpp", "src/common.cpp", "src/multigrid_cycle_tests.cpp", "src/reshapers_tests.cpp", "src/smoothers_tests.cpp", "src/test_wrappers.cpp"],
    hdrs = ["include/arithmetic_tests.h", "include/common.h", "include/multigrid_cycle_tests.h", "include/reshapers_tests.h", "include/smoothers_tests.h", "include/test_wrappers.h"],
    deps = ["//:src"],
    visibility = ["//visibility:public"]
)