cc_library(
    name = "grid",
    srcs = ["grid/grid.cpp"],
    hdrs = ["grid/grid.h"],
    visibiliy = [":visibility:public"]
)

cc_test(
    name = "arithmetic_tests",
    srcs = ["src/main.cpp"],
    deps = [":common:tests"]
)
