cc_test(
    name = "cycling_tests",
    srcs = ["cycling_tests.cc"],
    deps = [
        "//common/tests:common_tests",
        "//cycling",
        "//grid",
        "@gtest//:gtest_main",
    ],
)
