cc_test(
    name = "smoothers_tests",
    srcs = ["smoothers_tests.cc"],
    deps = [
        "//common/tests:common_tests",
        "//smoothers",
        "//grid",
        "@gtest//:gtest_main",
    ],
)
